config/routes.rb
Rails.application.routes.draw do

  resources :comments do
    collection do
      delete :destroy_all
    end
  end
  
  resources :tweets do
    collection do
      delete :destroy_all
      delete :destroy
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/register' => 'users#new'
  post '/users' => 'users#create'

  get '/moderator' => 'moderator#index'
  get '/moderator/pullNewTweets' => 'moderator#pullNewTweets'
  get 'moderator/setKeyword' => 'moderator#setKeyword'
  post 'moderator/postKeyword' => 'moderator#postKeyword'

  delete '/moderator/deleteAllUnapprovedTweets' => 'tweets#deleteAllUnapproved'
  put '/moderator/approveAllTweets' => 'tweets#approveAll'

  delete '/moderator/deleteAllUnapprovedComments' => 'comments#deleteAllUnapproved'
  put '/moderator/approveAllComments' => 'comments#approveAll'

  root 'pages#home'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    @commentsArray ||= Array.new
    @comments.each do |comment|
        if comment.filtered == true
           @commentsArray.push("<h3><b>#{comment.name}</b></h3><p style=\"margin-top: 5px; color:black\">#{comment.comment}</p>".html_safe)
        end
      end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @tweet = Tweet.find(params[:id])
    if @tweet.present?
      @tweet.update_attribute(:filtered, "true")
    end
    flash[:success] = "Tweet was successfully approved."
    redirect_to moderator_url
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      flash[:success] = "Comment was successfully submitted for approval."
      redirect_to '/comments'
    else
      flash[:error] = "There was an error creating your comment."
      redirect_to '/comments/new'
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attribute(:filtered, "true")
      flash[:success] = "Comment were successfully approved."
      redirect_to moderator_url
    else
      flash[:error] = "There was an error approving the comment."
      redirect_to moderator_url
    end
  end

  def destroy_all
    if Comment.all.count >= 1 && Comment.delete_all(:filtered => true)
      flash[:success] = "All comments were successfully deleted."
      redirect_to moderator_url
    else
      flash[:error] = "There was an error deleting all comments."
      redirect_to moderator_url
    end
  end

  def deleteAllUnapproved
    if Comment.where(:filtered => false).count >= 1 && Comment.destroy_all(:filtered => false)
      flash[:success] = "All unapproved comments were successfully deleted."
      redirect_to moderator_url
    else
      flash[:error] = "There was an error deleting all unapproved comments."
      redirect_to moderator_url
    end
  end

  def approveAll
    if Comment.where(:filtered => false).count >= 1 && Comment.update_all( :filtered => true )
      flash[:success] = "All comments were successfully approved."
      redirect_to moderator_url
    else
      flash[:error] = "There was an error approving all comments."
      redirect_to moderator_url
    end
  end

  # DELETE /comments/1
  def destroy
    if @comment.destroy
      flash[:success] = "Comment was successfully deleted."
      redirect_to moderator_url
    else
      flash[:error] = "There was an error deleting the comment."
      redirect_to moderator_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :comment, :filtered)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br>
    <h3><%= f.label :name %><br></h3>
    <%= f.text_field :name, :id => "name_box" %>
  </div>
  <div class="field">
    <br>
    <h3><%= f.label :comment %><br></h3>
    <%= f.text_area :comment, :id => "comment_box" %>
  </div>
  <div class="actions">
    <br>
    <%= f.submit :class => "btn btn-info" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<html>
	<head>
	</head>
	<body>
		<div class="container">
			<h1>Editing Comment</h1>
			<%= render 'form' %>
		</div>
	</body>
</html>

app/views/comments/index.html.erb
<html>
  <head>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><a href="/">All</a></li>
        <li><a href="/tweets">Tweets</a></li>
        <li class="active"><a href="#">Comments</a></li>
        <% if current_user %>
          <li><a href="/moderator">Moderator</a></li>
        <% end %>
      </ul>
      <!-- Main body of page -->
      <p id="notice"><%= notice %></p>
      <div class="row">
        <div class="col-md-6">
          <%= link_to 'New Comment', new_comment_path, :class => "btn btn-info" %>
        </div>
      </div>

      <!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>-->

<!-- Modal -->


      <div class="row">
        <% @commentsArray.each do |comment| %> 
          <div class="col-md-6 tweet">
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal3" style="background: white; outline: none; border: none; width: 100%; height: 100%; white-space: normal; text-align: left">
            <div class="module">
              <div class="module-body" style: "margin-left: 0px; color:black;">
                <%= comment %>
              </div>
              
            </div>
            </button>
          </div>
        <% end %>
      </div>
    </div>


    <div class="modal fade" id= "myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="margin-top: 10%">
      <div class="modal-dialog vertical-align-center">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

          </div>
          <div class="modal-body" id="modalBody3">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
        </div>
      </div>
  </body>
</html>

app/views/comments/new.html.erb
<html>
    <style>
      #name_box{
        width:30%;
      }
      #comment_box {
        width:60%;
        height:200px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>New Comment</h1>
      <%= render 'form' %>
    </div>
</body>
</html>

app/views/comments/show.html.erb
<html>
	<head>
	</head>
	<body>
		<div class="container">
		<p id="notice"><%= notice %></p>

		<div class="row">
			<div class="col-md-6">
				<div class="module">
					<div class="module-body">

						<p>
				  			<strong>Name:</strong>
				  			<%= @comment.name %>
						</p>

						<p>
						  <strong>Comment:</strong>
						  <%= @comment.comment %>
						</p>
					</div>
				</div>
			</div>	
		</div>
		<button type="submit" class="btn btn-default" ><%= link_to 'New Comment', new_comment_path %></button>
		<!--<button type="submit" class="btn btn-default" ><%= link_to 'Edit Comment', edit_comment_path(@comment) %></button>-->
		</div>
	</body>
</html>